<?php
// $Id$

/**
 * @file
 * Presents the fronpage, /node (slashnode) as json.
 * @author Bèr Kessels <ber@webschuur.com>
 * @link http://webschuur.com
 * @package slash_jason
 */

/* -----------------------------------------------------------------

  Hook Implementations

------------------------------------------------------------------ */

/**
 * Implementation of hook_menu().
 */
function slash_jason_menu() {
  $items = array();

  $items['node/json'] = array(
    'title' => 'slash_jason',
    'page callback' => 'slash_jason_page',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Renders frontpage-node-listings as json.
 *
 * @param 
 *   Description of param 
 *
 * @return
 *   String json.
 */
function slash_jason_page() {
  $nodes = array();
  
  $result = db_query(db_rewrite_sql('SELECT n.nid, n.sticky, n.created FROM {node} n WHERE n.promote = 1 AND n.status = 1 ORDER BY n.sticky DESC, n.created DESC'));

  while ($node = db_fetch_object($result)) {
    $nodes[] = node_load($node->nid);
  }

  drupal_json($nodes);
}
