<?php
// $Id$

/**
 * @file
 * Shows listings from an Etsy store in your Drupalsite.
 * @author Bèr Kessels <ber@webschuur.com>
 * @link http://webschuur.com
 * @package etsy
 */

/* -----------------------------------------------------------------

  Hook Implementations

------------------------------------------------------------------ */

/**
 * Implementation of hook_menu().
 */
function etsy_menu() {
  $items = array();

  $items['admin/settings/etsy'] = array(
    'title' => 'etsy',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('etsy_settings'),
    'access arguments' => array('administer etsy'),
    'file' => 'etsy.admin.inc',
  );

  return $items;
}
