<?php
// $Id$

/**
 * @file
 * Shows listings from an Etsy store in your Drupalsite.
 * @author Bèr Kessels <ber@webschuur.com>
 * @link http://webschuur.com
 * @package etsy
 */

/* -----------------------------------------------------------------

  Hook Implementations

------------------------------------------------------------------ */

/**
 * Implementation of hook_menu().
 */
function etsy_menu() {
  $items = array();

  $items['etsy'] = array(
    'title' => 'etsy',
    'page callback' => 'etsy_listings',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * REnders a single etsy shop
 *
 * @return
 *   HTML for an etsy shop.
 */
function etsy_listings() {
  $html  = '';

  $shop = _etsy_listings_get();
  $html = _etsy_listings_render($shop);
  
  return $html;
}


/**********************************************************************************
 *                            PRIVATE FUNCTIONS                                   *
 **********************************************************************************/
/**
 * Gets the listings from the ETSY api_key
 *
 * @return
 *   A $shop object. 
 */
function _etsy_listings_get() {
  $shop = new StdClass();

  module_load_include('inc', 'etsy', 'secret');
  $url = ETSY_API_URL .'shops/5304925/listings/active?includes=Images&api_key='. ETSY_API_KEY;

  $response = drupal_http_request($url);
  
  if (!$response) {
    $shop->results = array();
  }
  elseif ($response->code < 400) {
    $shop = json_decode($response->data);
  }
  
  
  return $shop;
}
/**
 * Themes(not really!) salable items
 *
 * @param $salable
 *   A $salable shop-item
 *
 * @return
 *   Items HTML
 */
function _etsy_listings_render($shop) {
  $html = '';
  drupal_add_css(drupal_get_path('module', 'etsy') .'/css/etsy.css');
  
  if (count($shop->results) <= 0 ) {
    drupal_set_message(t('Shop is empty :('));
  }

  foreach ($shop->results as $salable) {
    $link = l($salable->title, $salable->url);
    $html .= "<div class=\"etsy-salable\"><h3>{$link}</h3>";

    if ($img_url = $salable->Images[0]->url_200x200) {
      $img = theme('image', $img_url, $salable->title, $salable->title, array(), FALSE);
      $html .= l($img, $salable->url, array('html' => TRUE));
    }
      
    $html .= "<span class=\"price\">Price: \${$salable->price}</span></div>";
  }
  
  return $html;
}
