<?php
// $Id$

/**
 * @file
 * Simple couch geo HTML page example thing
 * @author Bèr Kessels <ber@webschuur.com>
 * @link http://webschuur.com
 * @package couch_geo
 */

/* -----------------------------------------------------------------

  Hook Implementations

------------------------------------------------------------------ */

/**
 * Implementation of hook_menu().
 */
function couch_geo_menu() {
  $items = array();

  $items['couch_geo'] = array(
    'title' => 'couch_geo',
    'page callback' => 'couch_geo_page',
    'page arguments' => array('access content'),
  );

  return $items;
}

/**
 * Demo remote integration
 *
 * @return
 *   String, example hardcoded HTML
 */
function couch_geo_page() {
  drupal_add_css();
  drupal_add_js();

  $ugly == <<<UGLY
    lots of hardcoded HTML.
UGLY
}
