<?php
// $Id$

/**
 * @file
 * Integrates the popular Open Source ecommerce environment Spree over REST into your site.
 * @author Bèr Kessels <ber@webschuur.com>
 * @link http://webschuur.com
 * @package spree
 */

/* -----------------------------------------------------------------

  Hook Implementations

------------------------------------------------------------------ */

/**
 * Implementation of hook_menu().
 */
function spree_menu() {
  $items = array();

  $items['admin/settings/spree'] = array(
    'title' => 'spree',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spree_settings'),
    'access arguments' => array('administer spree'),
    'file' => 'spree.admin.inc',
  );

  return $items;
}
